### ISSUE TITLE
Deployment of Solr for MFIN Data Catalogue

### ISSUE THREAD

**Issue by sylus** [bcgov/MFIN-Data-Catalogue#42]
## Overview

MFIN Data Catalogue will be using the Search API Solr Backend instead of the Search API DB Backend.

Solr is much more performant against large datasets, and provides many additional features.

* Improved file contents indexing
* Superior performance especially when dealing with numerous facets
* Better keywords handling
* Complete features like stemming, highlighting, spellchecking and phrase queries

There are two ways we can launch Solr:

* [Install Solr via Helm Chart](https://github.com/bitnami/charts/tree/main/bitnami/solr)
* [Install Solr through the Solr Operator](https://github.com/apache/solr-operator)

I have a fair bit of experience with both but Solr Operator is superior due to:

* Managing the full lifecycle of Solr
* Providing a default secure configuration of Solr
* Solr being run in Solr Cloud mode in a distributed fashion under Zookeeper
* Created and maintained by Apache and Lucidworks so is officially supported

## Blocker(s)

- [ ] BC Gov Platform Team Install Solr Operator
- [ ] Quota increase approved from storage-16 to storage-32

The BCGov Platform team would need to install the Solr Operator and I am not sure of the desire for them to do that. Although the Solr Operator does align with their model and they do install a great many other operators providing them to the users of the BC Gov Platform. 

If the platform team signals low interest or the time period for such a feature is prohibited then Solr can just be installed via the Helm Chart method and run as a stand alone container. However the client should still be consulted and informed of the direction and some of the downsides.

## Stack Overflow

I have created an issue asking about this over at BC Gov Stack Overflow:

* https://stackoverflow.developer.gov.bc.ca/questions/1111

The BCGov Platform team is assessing the request on June 29th and will report back.

In the meantime I have prepared Solr as a Helm Chart and just waiting for a quota increase / approval before I can successfully deploy

**Comment by sylus** [comment]
## Configuration of Solr Operator

```
apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  annotations:
    meta.helm.sh/release-name: mfin-data-catalogue-solr
    meta.helm.sh/release-namespace: ea352d-dev
  labels:
    app.kubernetes.io/instance: mfin-data-catalogue-solr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mfin-data-catalogue-solr
    app.kubernetes.io/version: 8.11.1
    helm.sh/chart: solr-0.1.7
  name: mfin-data-catalogue-solr
  namespace: ea352d-dev
spec:
  busyBoxImage:
    repository: library/busybox
    tag: 1.28.0-glibc
  customSolrKubeOptions:
    podOptions:
      livenessProbe:
        timeoutSeconds: 5
      readinessProbe:
        timeoutSeconds: 5
      resources:
        limits:
          memory: 5Gi
        requests:
          cpu: 65m
          memory: 156Mi
  dataStorage:
    persistent:
      pvcTemplate:
        metadata: {}
        spec:
          resources:
            requests:
              storage: 5Gi
      reclaimPolicy: Delete
  replicas: 1
  solrAddressability:
    commonServicePort: 80
    podPort: 8983
  solrGCTune: '-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8'
  solrImage:
    repository: library/solr
    tag: 8.11.1
  solrJavaMem: '-Xms1g -Xmx5g'
  solrLogLevel: INFO
  solrOpts: '-Dsolr.autoSoftCommit.maxTime=10000 -Dlog4j2.formatMsgNoLookups=true'
  solrSecurity:
    authenticationType: Basic
    basicAuthSecret: rsams-solr-basic-auth
    probesRequireAuth: true
  updateStrategy:
    managed: {}
    method: Managed
  zookeeperRef:
    provided:
      chroot: /this/will/be/auto/created
      image:
        pullPolicy: IfNotPresent
        repository: pravega/zookeeper
        tag: 0.2.6
      persistence:
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: default
      replicas: 1
      zookeeperPodPolicy:
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 65m
            memory: 156Mi
```
