### ISSUE TITLE
ArgoCD Vault Plugin for Secret Handling

### ISSUE THREAD

**Issue by sylus** [bcgov/MFIN-Data-Catalogue#50]
## Overview

I am just filing this issue so can track the installation of the Argo CD Vault Plugin configured with an associated Argo CD instance.

* https://argocd-vault-plugin.readthedocs.io/en/stable/

The Platform team uses the gitops operator and it looks like this is a solved problem for installing the Argo CD Vault Plugin.

* https://github.com/redhat-developer/gitops-operator/issues/281

As we don't want to have secrets in the tenant-gitops-***** repo and instead have the values stored in Hashicorp Vault which only get interpolated during the sync / reconciliation phase of Argo CD. This facilitates having no secrets in our Application Manifests repo and is considered a best practice.

## Background

In my job as a senior Technical Architect of the Platform Team as Statistics Canada we use both Argo CD and the Argo CD Vault Plugin connected to Azure Key Vault and also to Hashicorp Vault (which BCGov uses) to great effect. 

While the issue I posted above with the gitops operator posts what needs to be done I also posted the spec we used in case there is any difference in the comments below.

## Blocker(s)

- [ ] BC Gov Platform Team Install Argo CD Vault Plugin

The BCGov Platform team would need to install the Argo CD Vault Plugin and configure it to be linked with the Argo CD instance dedicated to a project.

I was talking with Ian Watts who mentioned the following:

> When we first introduced the shared instance of ArgoCD for teams to use, it wasn't possible to use the Vault plugin. I'll check my notes on that, though. Now that we have migrated to the GitOps Operator, it's worth another look."

## Stack Overflow

I have created an issue asking about this over at BC Gov Stack Overflow:

* https://stackoverflow.developer.gov.bc.ca/questions/1110

**Comment by sylus** [comment]
## Configuration of Argo CD Instance

```
"sidecarContainers" = [
  {
    "name"    = "avp"
    "command" = ["/var/run/argocd/argocd-cmp-server"]
    "image"   = "artifactory.example.ca/docker/platform/argocd:v1.0.0"
    "env" = [
      {
        "name"  = "ARGOCD_ENV_AVP_TYPE"
        "value" = "azurekeyvault"
      }
    ]
    "securityContext" = {
      "runAsNonRoot" = true
      "runAsUser"    = 999
    }
    "volumeMounts" = [
      {
        "name"      = "var-files"
        "mountPath" = "/var/run/argocd"
      },
      {
        "name"      = "plugins"
        "mountPath" = "/home/argocd/cmp-server/plugins"
      },
      {
        "name"      = local.cns_avp_configmap_name
        "subPath"   = "avp.yaml"
        "mountPath" = "/home/argocd/cmp-server/config/plugin.yaml"
      }
    ]
  },
  {
    "name"    = "avp-helm"
    "command" = ["/var/run/argocd/argocd-cmp-server"]
    "image"   = "artifactory.example.ca/docker/platform/argocd:v1.0.0"
    "env" = [
      {
        "name"  = "ARGOCD_ENV_AVP_TYPE"
        "value" = "azurekeyvault"
      }
    ]
    "securityContext" = {
      "runAsNonRoot" = true
      "runAsUser"    = 999
    }
    "volumeMounts" = [
      {
        "name"      = "var-files"
        "mountPath" = "/var/run/argocd"
      },
      {
        "name"      = "plugins"
        "mountPath" = "/home/argocd/cmp-server/plugins"
      },
      {
        "name"      = local.cns_avp_configmap_name
        "subPath"   = "avp-helm.yaml"
        "mountPath" = "/home/argocd/cmp-server/config/plugin.yaml"
      }
    ]
  }
]
```

**Comment by sylus** [comment]
## Configuration of Argo Vault Plugin

```
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-vault-plugin
spec:
  allowConcurrency: true
  discover:
    find:
      command:
        - sh
        - "-c"
        - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
  generate:
    command:
      - argocd-vault-plugin
      - generate
      - "."
  lockRepo: false
EOT
      "avp-helm.yaml" = <<EOT
---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-vault-plugin-helm
spec:
  allowConcurrency: true
  discover:
    find:
      command:
        - sh
        - "-c"
        - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
  generate:
    command:
      - bash
      - "-c"
      - 'helm template --include-crds $ARGOCD_ENV_HELM_RELEASE_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo "$ARGOCD_ENV_HELM_VALUES") . | argocd-vault-plugin generate -'
  lockRepo: false
```
