### ISSUE TITLE
Revisit DevOps team membership

### ISSUE THREAD

**Issue by danhgov** [bcgov/MFIN-Data-Catalogue#575]
Currently, our DevOps team is still set up as it was by Openplus. (If you're logged into Openshift, you can see this in [this GitOpsTeams object definition in ea352d-tools](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/ea352d-tools/warden.devops.gov.bc.ca~v1alpha1~GitOpsTeam/gitopsteam-ea352d/yaml).)

gitOpsMembers / admins have 

> full admin access to the repo, including repo deletion, adding of users. Recommended for people who need full access to the project, including sensitive and destructive actions like managing security or deleting a repository.

```
gitOpsMembers:
    admins:
      - sylus
      - chrislaick
      - danhgov
      - dhofman-bcgov
      - kardamk
```
Project Members / Maintainers have
> full access to the Argo CD Project, including the ability create, edit, and delete Applications within the Project.

```
  projectMembers:
    maintainers:
      - william.hearn@gov.bc.ca
      - liam.morland@gov.bc.ca
      - craig.clark@gov.bc.ca
      - stephen.mulvihill@gov.bc.ca
      - chris.lai@gov.bc.ca
      - dan.howard@gov.bc.ca
      - dan.hofman@gov.bc.ca
      - kunal.kardam@gov.bc.ca
```

@NicoledeGreef, how would you like to see these lists edited, or are you ok with them as-is?

**Comment by NicoledeGreef** [comment]
Thanks for the ticket, @danhgov .

gitOpsMembers:
    admins:
      -->please remove: 
       - sylus

  projectMembers:
    maintainers:
  -->please remove:
      - william.hearn@gov.bc.ca
      - liam.morland@gov.bc.ca
      - craig.clark@gov.bc.ca
      - stephen.mulvihill@gov.bc.ca

**Comment by chrislaick** [comment]
@NicoledeGreef This task is complete.

```
spec:
  gitOpsMembers:
    admins:
      - chrislaick
      - danhgov
      - dhofman-bcgov
      - kardamk
  projectMembers:
    maintainers:
      - chris.lai@gov.bc.ca
      - dan.howard@gov.bc.ca
      - dan.hofman@gov.bc.ca
      - kunal.kardam@gov.bc.ca
...
  projectMembers:
    maintainers:
      - chris.lai@gov.bc.ca
      - dan.hofman@gov.bc.ca
      - dan.howard@gov.bc.ca
      - kunal.kardam@gov.bc.ca
  repositoryMembers:
    admins:
      - chrislaick
      - danhgov
      - dhofman-bcgov
      - kardamk
```
